# Generated by Django 3.1.5 on 2021-01-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_auto_20210129_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='billing_address_line',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='billing_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='billing_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='billing_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='billing_street',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_timezone',
        ),
    ]
