# Generated by Django 3.1.5 on 2021-01-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0003_auto_20210129_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='city',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='postcode',
            new_name='billing_postcode',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='state',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='street',
            new_name='billing_street',
        ),
    ]
