# Generated by Django 3.1.5 on 2021-02-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0004_auto_20210129_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='follow_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='follow_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(null=True),
        ),
    ]
