# Generated by Django 3.1.5 on 2021-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0008_auto_20210204_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
