# Generated by Django 3.1.5 on 2021-02-06 18:59

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0009_orderitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
