# Generated by Django 3.1.5 on 2021-02-10 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0010_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDataFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
