# Generated by Django 3.1.5 on 2021-02-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0010_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
