# Generated by Django 3.1.5 on 2021-02-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0015_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
