# Generated by Django 3.1.5 on 2021-02-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0017_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
